server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: ${service-url.user-service}/user/getByUsername
          predicates:
            - Query=username

